app = "durak-discord-activity"
primary_region = "iad"

[deploy]
  kill_timeout = "35s"

[build]
  dockerfile = "Dockerfile"
  [build.args]
    VITE_DISCORD_CLIENT_ID = ""

[env]
  PORT = "2567"

[http_service]
  internal_port = 2567
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
  sticky_sessions = true

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512
